### ISSUE TITLE
Error message overflow

### ISSUE THREAD

**Issue by KrissiHub** [automl/DeepCAVE#100]
When a specific line of a thrown error message in the deepcave client is too long, there is a chance that it overflows, like such:
<img width="569" alt="Bildschirmfoto 2023-12-07 um 10 55 45" src="https://github.com/automl/DeepCAVE/assets/59476399/7cd3f629-d6f4-4075-99b7-b19d3ff0aecf">
To recreate, you would need to have to have an error in a file with a long pathname.

**Comment by helegraf** [comment]
Will be addressed by #101
