### ISSUE TITLE
No notification when trying to add a group with no name

### ISSUE THREAD

**Issue by KrissiHub** [automl/DeepCAVE#108]
In "General" in the web application, when trying to add a group without giving it a name, the group just disappears.
This may be a bit confusing, a notification would be nice, just something simple, like:
"You have to give your group a name before adding it." or something similar.

How to recreate:
Add multiple runs to a group in DeepCAVE, and click on "add" without entering a name.

Edit: Also, when adding a run that is not comparable with the group, it just disappears into the void. Would be great to include that in the fix.

**Comment by helegraf** [comment]
Plan: add an error upon entering an empty name for group and pre-fill with e.g. "Group 1"

**Comment by KrissiHub** [comment]
Additional: It would be nice to get a notification, (e.g. "You have to select runs first, before creating a group" or something like that), when trying to click on "add groups" without selecting a run first. At the moment if you click it, nothing happens, feedback is basically not there.
