### ISSUE TITLE
Varying configspace index order in PDP and symbolic explanations

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#111]
In the PDP plugin (similar in symbolic expl), the configspace is copied when creating the surrogate model
`        surrogate_model = RandomForestSurrogate(run.configspace, seed=0)`
and also when creating the PDP
`        pdp = PDP.from_random_points(`

In rare cases, this copying of the config space can lead to a different index order in the configspace. This is problematic, as we get the index of the selected hyperparameters from the original configspace, but then use it to select the correct index from the data produced by the PDP (with the changed index). 

For example, this occurs when using the run `logs/SMAC3v1/outlier-detection/DEHB-pendigits-015-0-0`  with
`hyperparameter_name_1="backbone:num_latent_units"`
to calculate the PDP.

**Comment by alexandertornede** [comment]
This seems to be caused by a faulty copy functionality of the underlying PDP package we are using. I reported the issue: https://github.com/dwoiwode/py-pdp-partitioner/issues/6

**Comment by sarah-segel** [comment]
Closed with #119
