### ISSUE TITLE
Random forest surrogate test is not actually executed

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#130]
The test `test_evaluators/random_forest_surrogate.py` is not actually being tested due to the filename not starting with `test`. When renamed and thus tested, the test fails. Thus, the test needs to be checked.

**Comment by helegraf** [comment]
Fixed with commit 104f18 "Fix test for random forest surrogate" (sorry accidentally committed to dev, brain is already in weekend mode).
