### ISSUE TITLE
Run names in logs are not really distinguishable

### ISSUE THREAD

**Issue by KrissiHub** [automl/DeepCAVE#138]
When adding multiple runs e.g. minimal/run_1 and mlp/run_1 it is not clear which one is which later on, because they are both called run_1. I find it a bit confusing, I think it would be nice to make it more obvious which run is which.
<img width="682" alt="Bildschirmfoto 2024-04-17 um 13 53 45" src="https://github.com/automl/DeepCAVE/assets/59476399/94bfede4-6bd3-4166-81f6-5de85cb39617">

**Comment by sarah-segel** [comment]
Adressed in https://github.com/automl/DeepCAVE/pull/146
