### ISSUE TITLE
Development diverged a lot from Main/ConfigSpace Issues

### ISSUE THREAD

**Issue by nikl234** [automl/DeepCAVE#177]
We were doing a project with SMAC3 and we had a lot of trouble with the current version of SMAC3 to get the current Version working with DeepCave, because of requirement Issues.

For example ConfigSpace==0.6.1 is in the main requirements.txt and so a requirement of the pip repository. We developed with the newest ConfigSpace Version and so we had troubles to install it Deepcave with pip. 

Afterwards we still had problems to run Deepcave, probably because of Problems with the new Features of ConfigSpace, but we didnt look that deeply into it, as it was hard to find the correct way to set DeepCAVE to be more verbose with its problems.
(It would be great if that would be documented).

**Comment by sarah-segel** [comment]
I am sorry to hear you faced such issues. We indeed have adapted DeepCAVE to the newest ConfigSpace and thus newest SMAC version on the development branch and will try to release that asap (probably beginning of next week).

Until then, if you want to use DeepCAVE, could you try to install from the development?
`pip install git+https://github.com/automl/DeepCAVE.git@development`

And, if you still experience issues with that, we'd of course be happy to hear about that.

**Comment by sarah-segel** [comment]
FYI: You can now use the standard pip install as the new version was released.
