### ISSUE TITLE
Display configids

### ISSUE THREAD

**Issue by timruhkopf** [automl/DeepCAVE#19]
When deepcave is the first pillar of my HPO run, I might find some particular configs (or sets of configs) interesting and would like to examine them further. To do so, I need to be able to select configs and be given back the ids

**Comment by renesass** [comment]
Integrated here [ec0abb9](https://github.com/automl/DeepCAVE/commit/ec0abb90696a88b0d83cf3e2bce18ef0cd9363d5)
