### ISSUE TITLE
[Compatibility] Issue with rq==2.0.0 in Python 3.10

### ISSUE THREAD

**Issue by becktepe** [automl/DeepCAVE#195]
Hi,

the current version of DeepCAVE does not support `v2.0.0 `of the `rq` package which is installed by default when following the instructions. It results in crashing background workers:
```
Traceback (most recent call last):
  File "/Users/jannisbecktepe/anaconda3/envs/deep_cave/lib/python3.10/site-packages/deepcave/worker.py", line 21, in <module>
    from rq import Connection, Worker
ImportError: cannot import name 'Connection' from 'rq' (/Users/jannisbecktepe/anaconda3/envs/autonnunet/lib/python3.10/site-packages/rq/__init__.py)
```

**Comment by LukasFehring** [comment]
Hi Jannis,
You can simply downgrade rq to 1.10.1.
But yes this needs to be fixed :)

**Comment by LukasFehring** [comment]
I will close this issue, since we merged a fix into main
