### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by JohannesHog** [automl/DeepCAVE#32]
I get the following error when trying to run `deepcave --open`: `ModuleNotFoundError: No module named 'smac.epm.util_funcs'`
I think smac changed the naming of the module from util_funcs to utils. 
The error occured in DeepCAVE/deepcave/evaluators/epm/random_forest.py and should be fixed if you change the import.

**Comment by renesass** [comment]
Yes, you are right. With the latest SMAC release, we changed some APIs. Restricting SMAC `smac<1.4.0` should fix this issue. Thanks for pointing out!
