### ISSUE TITLE
Pre-commit hooks: Check and update

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#42]
When doing a commit, error messages from the pre-commit hooks show up (with errors not regarding the changes made, but regarding the existing files). This needs to be checked and updated.

**Comment by eddiebergman** [comment]
It's always useful if you can provide the output, I can usually debug them from that without having to install :)

Fyi, you should know about `pre-commit autoupdate`

**Comment by sarah-segel** [comment]
@eddiebergman Thanks for the hint on the autoupdate command! 
After looking into the issue, it turned out that there was a problem with the flake config, not the pre-commit hook itself. Besides that, there still are some issues that we need to fix in the existing files to make all pre-commit hooks run through (i.e. errors from pydocstyle, mypy, flake8). We created a [branch](https://github.com/automl/DeepCAVE/tree/bug/pre-commit-hooks) for that and started to fix the issues, but did not yet finish. Not sure if you'd like to get involved in that though? ;)

**Comment by eddiebergman** [comment]
@sarah-segel I don't have the time on my plate unfortunatly as I know the typing issues are a bit non-trivial to solve, apologies.

**Comment by sarah-segel** [comment]
@eddiebergman Yes, this might take a little longer.. we plan to continue with it at our next DeepCAVE dev day ;)
