### ISSUE TITLE
Partial Dependence Plot: Fix seed

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#43]
There seems to be a problem with the reproducibility of the Partial Dependence Plot that needs to be checked.

**Comment by sarah-segel** [comment]
Should be checked if this is still the case, i.e. use the API to produce PDP plots and check if the results are reproducible.

**Comment by alexandertornede** [comment]
Seems to be fixed with #85 . Cannot reproduce the problem anymore. All plots are identical for me.
