### ISSUE TITLE
Plots: Make matplotlib outputs available for more plugins

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#45]
Plots are mainly created with Plotly in DeepCAVE. For some plots, a matplotlib version is available as well. This should be added for more plugins.

**Comment by KrissiHub** [comment]
It looks like he method for the matplotlib version for (e.g.) the importances plugin returns a plotly, not a matplotlib though. Am I seeing this right or can someone clarify?

**Comment by sarah-segel** [comment]
So by default, a plotly is returned. But when selecting matplotlib style, the method `load_mpl_outputs()` should be used instead of `load_outputs()`: https://github.com/automl/DeepCAVE/blob/1851126c064a3120299250fb39b2c00d00abbc2e/deepcave/plugins/__init__.py#L506 
I think currently the plugins parteto front and importance have that method. E.g. for the importance plugin: https://github.com/automl/DeepCAVE/blob/1851126c064a3120299250fb39b2c00d00abbc2e/deepcave/plugins/hyperparameter/importances.py#L291
Does that answer your question, or did I overlook something there?

**Comment by sarah-segel** [comment]
Nevertheless, there seem to be some problems with the existing matplotlib methods. E.g. they use seaborn style, but seaborn is not in the requirements - I will add that. For the pareto front, it seems like there is another problem as well, which needs to be checked at some point (it creates a plot but does not show the pareto front).

**Comment by KrissiHub** [comment]
I think the main part of my problem of understanding the method lies here[
](https://github.com/automl/DeepCAVE/blob/1851126c064a3120299250fb39b2c00d00abbc2e/deepcave/plugins/hyperparameter/importances.py#L284-L288)
If my understanding is correct, the returned object is a plotly object, but the methods name suggest, that it returns a matplotlib object.

**Comment by sarah-segel** [comment]
Closed as matplotlib will be removed for now, see #168
