### ISSUE TITLE
"state" Key missing in Run object when visualising BOHB runs with DeepCAVE

### ISSUE THREAD

**Issue by f2010126** [automl/DeepCAVE#65]
Hi, :)

I wanted to use the DeepCAVE framework to visualise some runs from HpBandSter. (I can't use SMAC because it has some issues with multi-node runs. I've already posted it.)
In `deepcave.runs.converters.bohb`,  while creating the runs from the bohb Result object, there is no "state" key in the info dict for the run Object within `bohb.get_all_runs()`.

Line 66 in deepcave/runs/converters/bohb.py
```
status = bohb_run.info["state"]
```

The bohb.py code assumes the configspace is also saved but it does not happen by default in the library. I've saved the configspace.json separately , while the `hpbandster.core.result.json_result_logger` saves results.json and configs.json.

Am I using the wrong version of HpBandSter? I used `pip install hpbandster` which installs version  0.7.4.

Warm Regards,

**Comment by sarah-segel** [comment]
Thank you for bringing that to our attention! 

So regarding the "state" key, you are right that this is not added to the info dict by default in HpBandSter (it could be added by the user to track if certain trials were not successful). However, if no information is added by the user, it should of course still be possible to load the run into DeepCAVE. We now adapted the DeepCAVE converter (#169) such that a trial is considered a SUCCESS if no state information is provided.

Regarding the Configspace, it is correct that the `configspace.json` needs to be saved by the user when running HpBandSter. We will add a note on this in the Documentation.
