### ISSUE TITLE
Local Importance shows the same graph for all objectives

### ISSUE THREAD

**Issue by daphne12345** [automl/DeepCAVE#71]
With Hyperparameter importance, if you select "local Importance", the same graph is displayed for all objectives. If you select Fanova, however, different graphs are displayed.

**Comment by sarah-segel** [comment]
See for example this run:
[mo_run.zip](https://github.com/automl/DeepCAVE/files/14219726/mo_run.zip)

**Comment by alexandertornede** [comment]
Should be fixed with #113
