### ISSUE TITLE
Hyperparameter Importance: Different values for same run

### ISSUE THREAD

**Issue by daphne12345** [automl/DeepCAVE#72]
When using the API and calculating the importance of a run more than one time, the importance values vary a lot. This happens for fANOVA and Local importance. An example code is here (execute more than once and compare the values):

```
from deepcave.runs.converters.smac3v2 import SMAC3v2Run
from deepcave.evaluators.fanova import fANOVA
from deepcave.evaluators.lpi import LPI
import pandas as pd

run = SMAC3v2Run.from_path("../smac3_output/700b9ad7b27ba991278b31467cbe7fe6/700b9ad7b27ba991278b31467cbe7fe6/")
result = fANOVA(run)
result.calculate(objectives=run.get_objective('1-accuracy'), budget=max(run.get_budgets()), n_trees=10, seed=None)
df_importance = pd.DataFrame(result.get_importances(hp_names=None))
df_importance[df_importance>0].dropna(axis=1)
```

**Comment by alexandertornede** [comment]
The code above does not work anymore since you cannot set a seed to `None` anymore with the changes made in the PR #85 . However, with the changes made in #85, you can simply not set the seed and still get the same results (as it is set to 0 by default). As such, we can close this issue.
