### ISSUE TITLE
Seaborn-related error on start of DeepCAVE

### ISSUE THREAD

**Issue by sarah-segel** [automl/DeepCAVE#82]
Starting DeepCAVE, the error

`OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in "style.available")`

is returned. This happens for me both with and without seaborn being installed.

**Comment by elya5** [comment]
Just stumpled across this error. The style names of matplotlib changed. It works with older version, e.g. `matplotlib==2.2.*`

**Comment by sarah-segel** [comment]
The error should be fixed not with the latest release.
