### ISSUE TITLE
Recorder doesn't allow dict configs even though signature says so

### ISSUE THREAD

**Issue by TheEimer** [automl/DeepCAVE#89]
Because the ID is used as a dict key, the config can't be a dictonary in the recorder. Typing says otherwise and the error isn't very clear, this should be checked and also dict removed from the types.

**Comment by KrissiHub** [comment]
I deleted the Type Hint in the signature, indicating that is if fine if the config is a dict (in the bug/pre-commit branch).
It only accepts Configurations now.
